let listOfStuff = [
  'animals',
  'astronomy',
  'astronomy',
  'biology',
  'chemistry',
  'chemistry',
<<<<<<< HEAD
  'earth science',
  'earth science',
  'electricity',
  'electricity',
  'inventions',
  'scientists and inventors',
  'animals',
  'ant',
  'archerfish',
  'bald eagle',
=======
  'earth-science',
  'earth-science',
  'electricity',
  'electricity',
  'inventions',
  'scientists-and-inventors',
  'animals',
  'ant',
  'archerfish',
  'bald-eagle',
>>>>>>> 7a9ae42bd616d64a9c3df688a5bd1b6e633a4345
  'bison',
  'butterfly',
  'cardinal',
  'cat',
  'cheetah',
  'clownfish',
  'crocodile',
  'dog',
  'dolphin',
  'dragonfly',
  'elephant',
  'flamingo',
  'frogs',
<<<<<<< HEAD
  'giant panda',
=======
  'giant-panda',
>>>>>>> 7a9ae42bd616d64a9c3df688a5bd1b6e633a4345
  'giraffe',
  'goldfish',
  'gorilla',
  'grasshopper',
  'hippopotamus',
  'horse',
  'kangaroo',
  'koala',
  'leopard',
  'lion',
  'lionfish',
<<<<<<< HEAD
  'mallard duck',
  'ostrich',
  'penguin',
  'peregrine falcon',
=======
  'mallard-duck',
  'ostrich',
  'penguin',
  'peregrine-falcon',
>>>>>>> 7a9ae42bd616d64a9c3df688a5bd1b6e633a4345
  'rhinoceros',
  'scorpion',
  'shark',
  'snake',
  'spiders',
  'swordfish',
  'tardigrades',
  'tiger',
  'turtle',
  'whale',
  'astronomy',
<<<<<<< HEAD
  'asteroids and meteors',
  'black holes',
  'comets',
  'galaxies',
  'hubble space telescope',
  'international space station',
  'jupiter',
  'kuiper belt',
  'mars',
  'mercury',
  'milky way',
  'moon',
  'neptune',
  'neutron star',
  'oort cloud',
  'planet earth',
  'pluto',
  'saturn',
  'solar system',
=======
  'asteroids-and-meteors',
  'black-holes',
  'comets',
  'galaxies',
  'hubble-space-telescope',
  'international-space-station',
  'jupiter',
  'kuiper-belt',
  'mars',
  'mercury',
  'milky-way',
  'moon',
  'neptune',
  'neutron-star',
  'oort-cloud',
  'planet-earth',
  'pluto',
  'saturn',
  'solar-system',
>>>>>>> 7a9ae42bd616d64a9c3df688a5bd1b6e633a4345
  'spacecraft',
  'stars',
  'sun',
  'universe',
  'uranus',
  'venus',
  'biology',
  'bacteria',
  'blood',
  'brain',
  'cancer',
  'carbohydrates',
  'cell',
<<<<<<< HEAD
  'classification of living things',
  'coronavirus',
  'diabetes',
  'digestive system',
  'dna',
  'enzymes',
  'fungi',
  'immune system',
  'influenza',
  'kingdoms',
  'life cycle of cells',
  'lipids',
  'microscope',
  'muscular system',
  'nervous system',
  'organs',
  'proteins',
  'protists',
  'skeletal system',
  'skin',
  'virus',
  'vitamins and minerals',
  'chemistry',
  'acids and basis',
  'aluminum',
  'calcium',
  'carbon',
  'chemical bonding',
  'chemical reactions',
=======
  'classification-of-living-things',
  'coronavirus',
  'diabetes',
  'digestive-system',
  'dna',
  'enzymes',
  'fungi',
  'immune-system',
  'influenza',
  'kingdoms',
  'life-cycle-of-cells',
  'lipids',
  'microscope',
  'muscular-system',
  'nervous-system',
  'organs',
  'proteins',
  'protists',
  'skeletal-system',
  'skin',
  'virus',
  'vitamins-and-minerals',
  'chemistry',
  'acids-and-basis',
  'aluminum',
  'calcium',
  'carbon',
  'chemical-bonding',
  'chemical-reactions',
>>>>>>> 7a9ae42bd616d64a9c3df688a5bd1b6e633a4345
  'chlorine',
  'copper',
  'crystals',
  'elements',
  'gold',
  'helium',
  'hydrogen',
  'iron',
  'lead',
  'magnesium',
<<<<<<< HEAD
  'mercury element',
  'molecules',
  'nickel',
  'nitrogen',
  'organic chemistry',
  'oxygen',
  'periodic table',
=======
  'mercury-element',
  'molecules',
  'nickel',
  'nitrogen',
  'organic-chemistry',
  'oxygen',
  'periodic-table',
>>>>>>> 7a9ae42bd616d64a9c3df688a5bd1b6e633a4345
  'platinum',
  'radioactivity',
  'silicon',
  'silver',
  'sodium',
<<<<<<< HEAD
  'states of matter',
  'sulfur',
  'titanium',
  'uranium',
  'what is atom',
  'zinc',
  'earth science',
  'air pollution',
  'atmosphere',
  'biomass energy',
  'carbon cycle',
  'caves',
  'clouds',
  'composition of the earth',
=======
  'states-of-matter',
  'sulfur',
  'titanium',
  'uranium',
  'what-is-atom',
  'zinc',
  'earth-science',
  'air-pollution',
  'atmosphere',
  'biomass-energy',
  'carbon-cycle',
  'caves',
  'clouds',
  'composition-of-the-earth',
>>>>>>> 7a9ae42bd616d64a9c3df688a5bd1b6e633a4345
  'deserts',
  'earthquake',
  'erosion',
  'fossils',
<<<<<<< HEAD
  'geothermal energy',
  'geysers',
  'glaciers',
  'global warming',
  'hurricane tropical cyclone',
  'hydropower',
  'ice ages',
  'lakes',
  'land pollution',
  'minerals',
  'mountains',
  'oceans',
  'ozone layer',
  'plate tectonics',
  'rainforest',
  'rocks',
  'seasons',
  'solar energy',
  'tidal energy',
  'tornado',
  'tsunamis',
  'volcano',
  'water cycle',
  'water pollution',
  'weather',
  'wind energy',
  'electricity',
  'batteries',
  'conductors and insulators',
  'digital electronics',
  'electric motor',
  'electronic circuit',
  'how electricity is made',
  'magnetism',
  'ohms law',
  'relay',
  'resistors capacitors and inductors',
  'transformer',
  'voltage current and resistance',
  'what is electricity',
  'inventions',
  'car',
  'invention of airplane',
  'invention of bicycle',
  'invention of camera',
  'invention of cotton gin',
  'invention of diesel engine',
  'invention of the hot air balloon',
  'invention of the light bulb',
  'invention of the sewing machine',
  'invention of the telescope',
=======
  'geothermal-energy',
  'geysers',
  'glaciers',
  'global-warming',
  'hurricane-tropical-cyclone',
  'hydropower',
  'ice-ages',
  'lakes',
  'land-pollution',
  'minerals',
  'mountains',
  'oceans',
  'ozone-layer',
  'plate-tectonics',
  'rainforest',
  'rocks',
  'seasons',
  'solar-energy',
  'tidal-energy',
  'tornado',
  'tsunamis',
  'volcano',
  'water-cycle',
  'water-pollution',
  'weather',
  'wind-energy',
  'electricity',
  'batteries',
  'conductors-and-insulators',
  'digital-electronics',
  'electric-motor',
  'electronic-circuit',
  'how-electricity-is-made',
  'magnetism',
  'ohms-law',
  'relay',
  'resistors-capacitors-and-inductors',
  'transformer',
  'voltage-current-and-resistance',
  'what-is-electricity',
  'inventions',
  'car',
  'invention-of-airplane',
  'invention-of-bicycle',
  'invention-of-camera',
  'invention-of-cotton-gin',
  'invention-of-diesel-engine',
  'invention-of-the-hot-air-balloon',
  'invention-of-the-light-bulb',
  'invention-of-the-sewing-machine',
  'invention-of-the-telescope',
>>>>>>> 7a9ae42bd616d64a9c3df688a5bd1b6e633a4345
  'television',
  'physics',
  'acceleration',
  'energy',
  'force',
  'gravity',
  'heat',
<<<<<<< HEAD
  'heat transfer',
  'how rainbows work',
  'lasers',
  'laws of motion',
  'mass and weight',
  'power',
  'radioactivity',
  'speed and velocity',
  'temperature',
  'what is friction',
  'what is light',
  'work',
  'plants',
  'cactus',
  'carnivorous plants',
  'cocoa beans',
  'flowering plants',
  'fruits and vegetables',
  'herbs',
  'how plants grow',
  'life cycle of plants',
  'non flowering plants',
  'photosynthesis',
  'plant defenses',
  'plant structure',
  'poisonous plants',
  'rainforest',
  'seed germination',
  'trees',
  'scientists and inventors',
  'albert einstein',
  'alessandro volta',
  'alexander graham bell',
  'archimedes',
  'benjamin franklin',
  'charles babbage',
  'charles darwin',
  'ernest rutherford',
  'galileo galilei',
  'humphry davy',
  'isaac newton',
  'james watt',
  'johannes gutenberg',
  'leonardo da vinci',
  'louis pasteur',
  'marie curie',
  'michael faraday',
  'nicolaus copernicus',
  'nikola tesla',
  'richard feynman',
  'robert boyle',
  'robert hooke',
  'samuel morse',
  'stephen hawking',
  'thomas edison',
  'william thomson lord kelvin'];
=======
  'heat-transfer',
  'how-rainbows-work',
  'lasers',
  'laws-of-motion',
  'mass-and-weight',
  'power',
  'radioactivity',
  'speed-and-velocity',
  'temperature',
  'what-is-friction',
  'what-is-light',
  'work',
  'plants',
  '-ways-plants-make-humans-healthy',
  'cactus',
  'carnivorous-plants',
  'cocoa-beans',
  'flowering-plants',
  'fruits-and-vegetables',
  'herbs',
  'how-plants-grow',
  'life-cycle-of-plants',
  'non-flowering-plants',
  'photosynthesis',
  'plant-defenses',
  'plant-structure',
  'poisonous-plants',
  'rainforest',
  'seed-germination',
  'trees',
  'scientists-and-inventors',
  'albert-einstein',
  'alessandro-volta',
  'alexander-graham-bell',
  'antoine-lavoisier',
  'archimedes',
  'avicenna-ibn-sina',
  'benjamin-franklin',
  'charles-babbage',
  'charles-darwin',
  'dmitri-mendeleev',
  'ernest-rutherford',
  'galileo-galilei',
  'humphry-davy',
  'ibn-al-haytham-alhazen',
  'ibn-al-nafis',
  'isaac-newton',
  'jabir-ibn-hayyan-geber',
  'james-watt',
  'johannes-gutenberg',
  'leonardo-da-vinci',
  'louis-pasteur',
  'marie-curie',
  'michael-faraday',
  'nasir-al-din-tusi',
  'nicolaus-copernicus',
  'nikola-tesla',
  'richard-feynman',
  'robert-boyle',
  'robert-hooke',
  'samuel-morse',
  'stephen-hawking',
  'thomas-edison',
  'william-thomson-lord-kelvin];asdfasdfasdfasdfasdfasd'];
  
// let x = Math.floor((Math.random() * listOfStuff.length) + 1);

>>>>>>> 7a9ae42bd616d64a9c3df688a5bd1b6e633a4345

function watchRandomResults() {
  $('.random_results').on('click', function() {
    event.preventDefault();
    let x = Math.floor((Math.random() * listOfStuff.length) + 1)
    let searchTerm=listOfStuff[x];
    $('#js-search-term').val(searchTerm);
  });
}

$(watchRandomResults);
